Fix `build.rs`: Use `env::var_os` to retrieve `Path`
briansmith/ring pull request #1580
Opened 2023-01-28 01:51 UTC by NobodyXu

- Fix retrieveing `OUT_DIR` in `build.rs`
 - Fix getting `CARGO_MANIFEST_DIR`: Use `env::var_os`
 - Modify `run_command_with_args` to take `OsStr` instead of `String` for args
 - Call `env::var_os` in `read_env_var`
 - Change return type to `PathBuf` instead of `String` for fn `compile`

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

2023-02-15 16:43 UTC, briansmith commented
Is the entire purpose of this PR to support non-Unicode(-compatible) paths? Is there any other goal with this PR?

2023-02-15 21:57 UTC, briansmith commented
I agree with the idea that we should be using `OsString`s for paths. Do you have a realistic example of a configuration that works with this PR but doesn't work without this PR, so I can understand the real-world implications better? Thanks in advance!

2023-02-16 00:50 UTC, NobodyXu commented
> Is the entire purpose of this PR to support non-Unicode(-compatible) paths? Is there any other goal with this PR?

Yes



> I agree with the idea that we should be using `OsString`s for paths. Do you have a realistic example of a configuration that works with this PR but doesn't work without this PR, so I can understand the real-world implications better? Thanks in advance!

Linux filename can be anything that is `\0` terminated and various unix program accepts anything that is ascii-compatible, that is, encoded in bytes and can use all ascii characters.

So the user can use arbitary non-unicode characters in their home dir or whatever dir, `cargo new --lib .` a project, then add this project as a dependency and tries to `cargo b` it.

Without non-unicode support, this will fail since the `CARGO_MANIFEST_DIR` is likely to be a absolute path.
It is also possible that `OUR_DIR` is a absolute path and even if it's not, the user could change the location and name of the `target` dir.

So it's possible for these environment variables to contain non-unicode and I'd like ring's `build.rs` to properly handle it.

2023-02-16 21:17 UTC, briansmith commented
> Linux filename can be anything that is \0 terminated and various unix program accepts anything that is ascii-compatible, that is, encoded in bytes and can use all ascii characters.

That is true, but if somebody is taking full advantage of that flexibility, it's really their own fault.

> Without non-unicode support, this will fail since the CARGO_MANIFEST_DIR is likely to be a absolute path.

I understand. I'm simply asking could you provide a plausible scenerio where `CARGO_MANIFEST_DIR` contains non-Unicode-compatible characters? For example, "If a user with username "X" tries to build *ring* when their system character set is Y then the build fails." I.e. something I could test out myself without feeling silly.

2023-02-17 01:19 UTC, NobodyXu commented
> I understand. I'm simply asking could you provide a plausible scenerio where CARGO_MANIFEST_DIR contains non-Unicode-compatible characters? For example, "If a user with username "X" tries to build ring when their system character set is Y then the build fails." I.e. something I could test out myself without feeling silly.

On linux, I am able to create a non-unicode dir by running:

```bash
mkdir $(printf '\xFF')
```

And then cd into it by running:

```bash
cd $(printf '\xFF')
```

I can create a user with non-unicode home:

```bash
adduser a --home /home/"$(printf 'a\xFF')"
```

and I can cd into its home using:

```bash
cd /home/a\377/
```

2023-02-17 21:30 UTC, briansmith commented
@NobodyXu Is this an issue that's causing trouble on a real system, or just a theoretical issue? `0xFF` in a path is a theoretical issue. This will help me prioritize this.

2023-02-18 00:55 UTC, NobodyXu commented
> @NobodyXu Is this an issue that's causing trouble on a real system, or just a theoretical issue? `0xFF` in a path is a theoretical issue. This will help me prioritize this.

Unfortunately I don't have any real world example for this, so right now it just stays as a theoretical issue, but I won't be surprised if somebody out there is having non-unicode path in their system, hence I think it's better to support any `Path`.

2023-10-06 03:38 UTC, briansmith requested changes
PTAL at #1698. Your changes here are more thorough #1698. I think it would be great if you could review #1698 and then rebase this on that. If you do I will review it and merge it right away.

2023-10-06 03:38 UTC, briansmith commented on build.rs
> +        Some(val) if val == OsStr::new("1") => {
You can do `Some(val) if val == "1"`; see #1698.

2023-10-06 03:38 UTC, briansmith commented on build.rs
> +fn run_command_with_args<S, Arg>(command_name: S, args: impl IntoIterator<Item = Arg>)
We should just get rid of the generics here; see #1698.

2023-10-06 11:28 UTC, NobodyXu commented
@briansmith I've rebased this PR against main, please review this.

2023-10-06 15:40 UTC, briansmith approved these changes
Thank you for doing this. If you have other things you want to clean up in build.rs I would be happy to work with you on them. PR #1699 is another one you may be interested in.

2023-10-06 15:40 UTC, briansmith commented on build.rs
> +) -> PathBuf {
Nice!

2023-10-06 15:40 UTC, briansmith commented on build.rs
> +    let _ = c.arg("-c").arg(arg).arg(file);
Also very nice.

2023-10-06 17:06 UTC, briansmith approved these changes

2023-10-06 17:06 UTC, merged

2023-10-06 17:06 UTC, briansmith commented
Thank you!