Refactor fe_isnonzero to fe_isnonzero_vartime
briansmith/ring pull request #1893
Opened 2024-01-11 15:17 UTC by tisonkun

This refers to #1827.

An intuitive solution according to @briansmith's comment. But I know little about crypto so perhaps some invariants are broken.

2024-01-11 23:29 UTC, briansmith requested changes
Thanks for tackling this.

2024-01-11 23:29 UTC, briansmith commented on Cargo.toml
> -    "crypto/mem.c",
We can't remove crypto/mem.c until #1899 is implemented.

2024-01-11 23:29 UTC, briansmith commented on Cargo.toml
> -    "include/ring-core/mem.h",
We should be able to remove mem.h with this PR though, if we remove the include from mem.c.

2024-01-11 23:29 UTC, briansmith commented on build.rs
> -    (&[], "crypto/mem.c"),
Ditto. We need to retain it for now.

2024-01-11 23:29 UTC, briansmith commented on build.rs
> -        "CRYPTO_memcmp",
Ditto.

2024-01-11 23:29 UTC, briansmith commented on crypto/curve25519/curve25519.c
> +  for (unsigned i = 0; i < 32; i++) {
We use `size_t` for array indexes. I think we should use `sizeof(s)` instead of `32`.

2024-01-11 23:29 UTC, briansmith commented on crypto/mem.c
> -#include <ring-core/mem.h>
We need to restore this file but remove this `#include`.

2024-01-11 23:29 UTC, briansmith commented on src/constant_time.rs
> +    if a != b {
We cannot do this because we need a constant-time comparison. See #1899.

2024-01-13 02:16 UTC, tisonkun commented
Thanks for your review @briansmith!

Do you think it's better to exclude changes in `src/constant_time.rs` and move forward this PR, or we can wait for https://github.com/briansmith/ring/pull/1899 merged?

2024-01-13 02:41 UTC, briansmith commented
Yes, I think we should limit this to the curve25519.c change and mem.h deletion.

2024-01-13 10:37 UTC, tisonkun commented
Updated. PTAL @briansmith.

2024-02-21 14:03 UTC, tisonkun commented on crypto/curve25519/curve25519.c
> -  static const uint8_t zero[32] = {0};
Thanks for your information! Updated.

2024-03-09 03:18 UTC, tisonkun commented
@briansmith ping as a reminder :D

2024-04-09 04:54 UTC, tisonkun commented
@briansmith I suppose the codecov regression is false positive..

2024-07-06 22:00 UTC, tisonkun commented
@briansmith is there other blocker to this PR?

2025-02-19 17:28 UTC, tisonkun commented
As #1827 resolved, this seems unrelated.

2025-02-19 17:28 UTC, closed without merging