ci: add support for loongarch64-unknown-linux-{gnu,musl}
briansmith/ring pull request #2159
Opened 2024-11-14 14:07 UTC by heiher

2024-12-05 21:02 UTC, briansmith requested changes
Thanks. I don't want to add these to the CI matrix because they are just going to be running the same code that is already tested in other targets and the matrix is already too huge. However, I would like to accept the changes to cargo.sh and install-build-tools.sh. Could you revert the changes to ci.yml and leave the rest? Thanks!

2024-12-05 21:02 UTC, briansmith commented on .github/workflows/ci.yml
> +          - loongarch64-unknown-linux-musl # Has assembly
There is no assembly in our code for these targets.

2024-12-06 03:33 UTC, heiher commented
> Thanks. I don't want to add these to the CI matrix because they are just going to be running the same code that is already tested in other targets and the matrix is already too huge. However, I would like to accept the changes to cargo.sh and install-build-tools.sh. Could you revert the changes to ci.yml and leave the rest? Thanks!

Thanks for your review. It's done.

2024-12-07 02:44 UTC, briansmith approved these changes

2024-12-07 02:44 UTC, merged